services:
  anaconda:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./notebooks:/opt/notebooks
    ports:
      - "80:8888"
    environment:
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
