version: "3.8"
services:
  anaconda:
    build: ./
    volumes:
      - ./notebooks:/notebooks
      - jupyter_data:/root/.jupyter
    ports:
      - "${PORT:-8888}:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_PASSWORD}
      - USE_JUPYTER_LAB=${USE_JUPYTER_LAB:-true}

volumes:
  jupyter_data:
